name: Java CI with Maven

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Google Chrome & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl gnupg2
          curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-linux-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y libnss3 libxi6 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxtst6 libxrandr2 libasound2t64 libpangocairo-1.0-0 libatk1.0-0 libcups2

      - name: Check if app URL is reachable
        run: curl -I https://opensource-demo.orangehrmlive.com/

      - name: Run Maven Tests
        run: mvn clean test
      - name: Copy screenshots into reports folder
        run: |
          mkdir -p reports/screenshots
          cp -r screenshots/* reports/screenshots/ || echo "No screenshots to copy"

      - name: Upload Extent Reports (with screenshots)
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: reports/

